Other Errors have been solved and then it Worked
-When the form has been completed, this error message got displayed "main.js:138 Uncaught TypeError: h1.addClass is not a function
    at formComplete (main.js:138)
    at inputPass (main.js:131)
    at validate (main.js:96)
    at HTMLInputElement.<anonymous> (main.js:38)"

-I solved it by changing addClass into classList.add

-Then, this error appeared after completing the form once again "main.js:141 Uncaught ReferenceError: question is not defined
    at formComplete (main.js:141)
    at inputPass (main.js:131)
    at HTMLElement.validate (main.js:96)"

- This one was solved by correcting a typo on line 141, which was supposed to be question's', not question.